name: Bad Elf
favicon: null
layout_spectrum: 1
typography_spectrum: 0.04915
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f4fc'
    - '#020101'
    - '#b6081c'
    - '#6d9003'
    - '#c8b809'
  brandStrength: 0.1875
  lightness: 0.4375
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
